#!/bin/bash

cd $( dirname $0 )
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple requests pika

echo
echo "# check_rabbitmq_unroutable_msg"
echo "###############################"
./check_rabbitmq_unroutable_msg /opt/config.ini.default

echo
echo "# wip_detect_broken_bindings"
echo "############################"
./wip_detect_broken_bindings

echo
echo "# wip_detect_broken_queues"
echo "##########################"
./wip_detect_broken_queues

